### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by wheatbread** [gflujan/mark-as-junk#11]
Hi,

I installed your addon and got the following error upon loading in:

`111x mark-item-as/Modules/Tooltip.lua:45: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@mark-item-as/Modules/Tooltip.lua"]:45: in function `SetGameTooltip'
[string "@mark-item-as/Modules/Tooltip.lua"]:25: in function <mark-item-as/Modules/Tooltip.lua:24>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "@AverageItemLevel/core.lua"]:529: in function <AverageItemLevel/core.lua:509>
[string "@AverageItemLevel/core.lua"]:599: in function `?'
[string "@AverageItemLevel/semlib/eve.lua"]:19: in function <AverageItemLevel/semlib/eve.lua:16>

Locals:
(*temporary) = nil
(*temporary) = "item:(%d+):"
(*temporary) = "string expected, got nil"
`

**Comment by metal-gabe** [comment]
@wheatbread thanks for reporting this. 🙂  I'll have a fix for it within the next day. I'll update this issue when it's ready.

**Comment by metal-gabe** [comment]
Hi @wheatbread, I've uploaded the fix for this. You should see the updated version (1.0.3) on CurseForge. 

I will close this issue, but if you run into any other bugs, please let me know. Thanks!
