### ISSUE TITLE
Addon not working apparently

### ISSUE THREAD

**Issue by DrruuEU** [gflujan/mark-as-junk#13]
Hi there,

I wanted to try your addon today to utilize it as a way to mark junk when going through my bags, and potentially sell it with another Addon ([Scrap](https://www.curseforge.com/wow/addons/scrap)).
However, it seems to fail at the marking process. I tried using any modifyer, any of the two MButton options but it doesn't seem to mark anything.
I have a bunch of addons loaded as well but I turned everything off except for MIA and it still doesn't seem to work.

A little help would be appreciated. 🙂

Best regards,
Drruu

**Comment by metal-gabe** [comment]
Hi @DrruuEU , I'm really sorry but I'm just seeing this now. 😞 I apologize for such a late reply but I've been using the add-on during this time, and marking in general has been working for me. 

Could you please provide me some info to help identify what's happening? 

1. What bag add-on (if any) are you using? 
2. Do you see any output in the chat when you're trying to mark an item? 
3. Are you able to use an add-on like [ItemLock](https://www.curseforge.com/wow/addons/itemlock)? 

Overall, MIA is not meant to integrate with Scrap. It will sell things on its own if you tell it to. 

Please let me know if you have any additional questions. Thanks for using the add-on!

**Comment by metal-gabe** [comment]
If you haven't already, one thing to try is in the `Chat` options section of MIA, enable the `"Show MIA command output?"` option and try marking something. Then if you see any output to please post it here.
